server.name: kibana
server.host: "0.0.0.0"

# Elasticsearch Connection
elasticsearch.hosts: [ "http://localhost:9200" ]


## X-Pack security credentials
elasticsearch.username: elastic
elasticsearch.password: ${ELASTIC_PASSWORD}
